{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentakserver.postgresql.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "opentakserver.postgresql.fullname" .) "key" "password" "length" 24 "providedValues" (list "postgresql.auth.password") "context" $) }}
  postgres-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "opentakserver.postgresql.fullname" .) "key" "postgres-password" "length" 24 "providedValues" (list "postgresql.auth.postgresPassword") "context" $) }}
{{- end }}
