{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentakserver.rabbitmq.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  rabbitmq-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "opentakserver.rabbitmq.fullname" .) "key" "rabbitmq-password" "length" 24 "providedValues" (list "rabbitmq.auth.password") "context" $) }}
{{- end }}
