{{- if .Values.webui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opentakserver.webui.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: webui
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.webui.autoscaling.enabled }}
  replicas: {{ .Values.webui.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: webui
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: webui
        {{- with .Values.webui.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
        {{- end }}
      {{- with .Values.webui.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "opentakserver.serviceAccountName" . }}
      {{- include "opentakserver.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.webui.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.webui.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      {{- with .Values.webui.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: webui
          image: {{ include "opentakserver.webui.image" . }}
          imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
          {{- if .Values.webui.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.webui.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.webui.containerPort }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.webui.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
{{- end }}
