{{- if not .Values.opentakserver.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secrets" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  secret-key: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-secrets" (include "common.names.fullname" .)) "key" "secret-key" "length" 64 "providedValues" (list "opentakserver.secretKey") "context" $) }}
  ca-password: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-secrets" (include "common.names.fullname" .)) "key" "ca-password" "length" 24 "providedValues" (list "opentakserver.ca.password") "context" $) }}
  {{- if .Values.mediamtx.enabled }}
  mediamtx-token: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-secrets" (include "common.names.fullname" .)) "key" "mediamtx-token" "length" 40 "providedValues" (list "mediamtx.apiToken") "context" $) }}
  {{- end }}
{{- end }}
{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-externaldb" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  password: {{ required "externalDatabase.password is required when postgresql.enabled=false and no existingSecret is set" .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
{{- if and (not .Values.rabbitmq.enabled) (not .Values.externalRabbitmq.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-externalrabbitmq" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  rabbitmq-password: {{ required "externalRabbitmq.password is required when rabbitmq.enabled=false and no existingSecret is set" .Values.externalRabbitmq.password | b64enc | quote }}
{{- end }}
